### ISSUE TITLE
Scrum Report Sprint 5 (July 7 - 20)

### ISSUE THREAD

**Issue by mingyugao** [achin797/tagify#51]

**Comment by mingyugao** [comment]
What I did
- refactor server code to use Meteor.users collection
- remove insecure
- remove autopublish

Major challenges I/we ran into
- After refreshing, the user's spotify id would be lost from the redux store. I tried several solutions to persist the spotify id through the refresh, but ended up realizing that using spotify id to was not necessary.

What I plan to do
- protected routes
- sign out
- refactor tags panel to always be editable and remove tags page
- fix up the home page UI
- cleanup page

**Comment by akvaale** [comment]
**What I did:**
- Add taggedSongs object array to the database
- Changed DB queries to use actual user SpotifyID 
- Endpoints for addSongTag, deleteSongTag & necessary respective changes to reducer/actions/components


**Major challenges:**
- I ran into difficulty while trying to check if a nested array within the MongoDB is empty. Eventually used filter and updated the db twice.
- Currently having trouble attempting to iterate through nested array in mongoDB. Will likely need to use the filter workaround again.

**What I plan to do:**
- Finalize the database implementation.
- Add a playlists page 
    - Display users existing playlists
    - Select and mass-apply tags to playlists
    - Remove tag from selected playlist

**Comment by achin797** [comment]
What I did:
• Render user's songs.
• Implemented generate playlist from tags feature.
• Added toggle for AND/OR tag filtering.
• Added a search filter.

Major challenges:
• Had a hard time implementing dynamic search filtering but was able to easily do it by adding the search component to the homepage.

What I plan to do:
• Implement search page to be able to add tags to songs not in the user's library.
• Have better naming for playlist generated from tags.
• add a state to selected tags where you're able to exclude a tag. Like this: https://community.spotify.com/t5/Closed-Ideas/All-Platforms-Playlists-Tag-music-and-create-playlist-based-on/idi-p/4568429
